all:
	cd linear_diffusion&&$(MAKE)
	cd not_quite_diffusion&&$(MAKE)
	cd burgers&&$(MAKE)
	cd implicit_euler&&$(MAKE)

clean:
	cd linear_diffusion&&$(MAKE) clean
	cd not_quite_diffusion&&$(MAKE) clean
	cd burgers&&$(MAKE) clean
	cd implicit_euler&&$(MAKE) clean

.PHONY: all clean

